# Generated by Django 4.1 on 2022-08-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField()),
                ('hijos', models.CharField(max_length=15)),
            ],
        ),
    ]
