# Generated by Django 4.1 on 2022-08-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flia', '0002_familiar1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apodo', models.CharField(max_length=40)),
                ('de_donde', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=40)),
                ('puesto', models.CharField(max_length=40)),
                ('tarea', models.CharField(max_length=250)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
